### PR TITLE
Improved the Template

### PR DESCRIPTION
**Pull request by savi-1311**
- Fixes Issue #15 
- Changed the template of the emails sent. (Fixed a typo that was in the previous PR)
- Made a minimalistic black and white design with few coloured graphics.
- Posting screenshots for a better review.

### invite.html
image

### finalChoice.html
image

### Key Changes made:
- Used relative path address for images. (./images/image_name)
- Imported Roboto font using the script tag from Google Fonts.
- Only changed the template folder, other files/folders are intact.
- Also kept the links intact in the HTML file.
- P.S: Also added a shine animation to the button.

### CODE REVIEW

**Comment by savi-1311** [comment]
@AnandBaburajan Can you review it?

**Comment by AnandBaburajan** [comment]
Thank you @savi-1311! Please make sure to create a new branch for each new PR and just curious, why did you close your previous PR? :D 

I also have a few suggestions on the template:

1. The top banner can be replaced with our official banner (can be found in the readme). I'll DM you the image.
2. You can maybe remove the headings ("Make sure to value your time, get voting" and "Meeting time declared").
3. You can remove the illustrations from both the templates and remove "Invite by" & "Poll title" in the first template as they're redundant.
4. In the first template, the second sentence should be "Mark your availability by selecting ~one of~ the time-slots that suit you. ~Click on the button...poll~". The mail should start with "Hi there, <line break>".
5. In the second template, the content could be "Hi there, <line break> the final time for the meet {{pollTitle}} has been announced. Visit the poll page to find out the timing."
6. Do you think it would be nice to have a outer background like: 
image
7. You can take inspiration from the above design for the footer.

**Comment by AnandBaburajan** [comment]
@anaswaratrajan & @AthulJoshi do you have any suggestions? @savi-1311 I understand that receiving feedback on design/UI may not much fun so thanks a lot for contributing!

**Comment by AnandBaburajan** [comment]
Also, the failing tests in CI are not your fault, so please don't mind. We're looking into it!

**Comment by savi-1311** [comment]
Sure! I'll work on the changes :) 
Thanks for the detailed feedback.
I'm a beginner in Open Source, so just made another PR because of a typo. Didn't know we could modify the same!

**Comment by AnandBaburajan** [comment]
> Sure! I'll work on the changes :)

:D

> Didn't know we could modify the same!

Yep, you can update the PR by pushing commits to the branch associated with the PR.

**Comment by anaswaratrajan** [comment]
> @anaswaratrajan and @AthulJoshi do you have any suggestions? @savi-1311 I understand that receiving feedback on design/UI may not be much fun so thanks a lot for contributing!

I agree with @AnandBaburajan's feedbacks. A minimalistic social media footer is a nice idea for better reach. Currently we have a [twitter](https://twitter.com/rocketmeethq), [linkedin](https://www.linkedin.com/company/rocketmeet/) and github page. Maybe also add our email rocketmeet@gmail.com with an email icon. You can find all the icons from [fontawesome](https://fontawesome.com/). 

I think using illustrations is a good idea if it helps the user. Just make sure to use free illustrations with no copyrights when doing so. But overall, lgtm. Thanks for your PR @savi-1311! :D

**Comment by AthulJoshi** [comment]
> @anaswaratrajan and @AthulJoshi do you have any suggestions? @savi-1311 I understand that receiving feedback on design/UI may not be much fun so thanks a lot for contributing!

I agree with the points @AnandBaburajan mentioned.

**Comment by AnandBaburajan** [comment]
@savi-1311 closing this PR since we're discontinuing the mailer service. Thanks for showing interest. :)

**Pull request closed without merging**
